<<<<<<< HEAD
  
language: csharp
solution: ./SpeakerMeet.sln 
dist: bionic
mono: none
dotnet: 3.1
install: 
    - dotnet restore
script:
    - dotnet build
    - dotnet test
=======
language: csharp
solution: ./SpeakerMeet.sln 
dist: bionic
mono: none
dotnet: 3.1
install: 
    - dotnet restore
script:
    - dotnet build
    - dotnet test
>>>>>>> 24337e49eeb0f25e8cc16ba49fbea38f18cab34a
